### ISSUE TITLE
Make the prototyper link configurable 

### ISSUE THREAD

**Issue by Mtze** [ls1intum/Prototyper#21]
The Prototyper instance is hardcoded in 
https://github.com/ls1intum/Prototyper/blob/6a0d0268335d0133649385787c9090790d8a5f8b/Sources/Prototyper/Model/APIHandler.swift#L50

We need a way to make this link configurable by the user. We now have multiple instances (for testing and production). 

@PSchmiedmayer ideas?

**Comment by PSchmiedmayer** [comment]
Closed with the https://github.com/ls1intum/Prototyper/releases/tag/2.0.0-rc.1 release
